theme = "bad-wolf"
icons = "awesome"

[[block]]
block = "pacman"
interval = 600
format = "Updates: {pacman}|{aur}"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux |linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "yay -Qua"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "cpu"
interval = 1
format = "{barchart}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"
step_width = 5

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "weather"
format = "{weather} {temp}°C"
service = { name = "openweathermap", api_key = "160bc0a8901641db0ae66193040a6f9c", city_id = "2838744", units = "metric" }

[[block]]
block = "time"
interval = 60
locale = "de_DE"
format = "%a %d/%m %R"
